---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  # - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[dev_env::pre_process]
      - recipe[dev_env::default]
    attributes: {
      dev_env: {
        user: "vagrant",
        packages: [
          { name: "curl" }
        ],
        gems: [
          { name: "tmuxinator" }
        ],
        apps: [
          {
            checkout_path: "/vagrant/home/projects/sample_app",
            git_repo: "git@github.com:railstutorial/sample_app.git",
            revision: "master",
            git_action: "checkout",
            user: "vagrant",
            post_commands: <<-EOH
              touch run_post_commands
            EOH
          }
        ]
      }
    }
